export default `
$#@$Fgdgdf df gdFGdfgdffgg @@ (fdfd (123/ 4343 : 554 $fdfdf $12323) ++*~~FDfd $$@@)

Lâu đài bay của pháp sư Howl (((444))) (ハウルの動く城 Hauru no Ugoku Shiro?, tựa tiếng Anh là Howl's Moving Castle), hay Lâu đài di động của Howl, là một bộ phim điện ảnh hoạt hình Nhật Bản thuộc thể loại kỳ ảo năm 2004 do Miyazaki Hayao đạo diễn kiêm viết kịch bản, dựa trên tiểu thuyết cùng tên năm 1986 của nữ tác giả người Anh Diana Wynne Jones. Bộ phim do Suzuki Toshio sản xuất, với phần đồ hoạ hoạt hình thuộc về Studio Ghibli và được phân phối bởi Toho. Hai diễn viên lồng tiếng chính cho phiên bản tiếng Nhật bao gồm Baisho Chieko và Kimura Takuya, trong khi đó các diễn viên lồng tiếng Anh gồm có Jean Simmons, Emily Mortimer và Christian Bale. Lấy bối cảnh một vương quốc hư cấu nơi mà cả phép thuật và công nghệ tiên tiến đầu thế kỷ 20 cùng tồn tại, câu chuyện xoay quanh Sophie, cô thợ làm mũ trẻ luôn bằng lòng với cuộc sống bình lặng của mình. Sau khi bị một mụ phù thủy yểm bùa biến thành bà già, Sophie gặp được pháp sư Howl và cùng anh đối đầu với nhà vua, người yêu cầu anh tham gia vào cuộc chiến tranh với nước láng giềng.
5 + 4.500000 = 9.500000 5 – 7 = -2 7 * 6.000000 = 42.000000 7 / 5 = 1 4.500000 / 5 = 0.900000 4.500000 / 6.000000 = 0.750000 7 % 5 = 2
Tác phẩm mang chủ đề phản chiến do ảnh hưởng từ sự phản đối của Miyazaki trước cuộc xâm lược Iraq của Hoa Kỳ năm 2003. Miyazaki khẳng định rằng ông "cực kì phẫn nộ" với cuộc chiến tranh này, do đó vị đạo diễn muốn làm một bộ phim mà ông nghĩ sẽ không được đón nhận ở Mỹ.[5] Phim cũng khai thác chủ đề tuổi già và miêu tả tuổi tác theo chiều hướng tích cực như là một điều mang lại sự tự do cho nhân vật chính. Tác phẩm còn chứa đựng các yếu tố nữ quyền và mang thông điệp về giá trị của lòng trắc ẩn. Năm 2013, Miyazaki chia sẻ rằng đây là tác phẩm yêu thích của ông trong số những đứa con tinh thần của mình, giải thích: "Tôi muốn truyền đi thông điệp rằng cuộc đời là đáng sống và tôi nghĩ điều đó chưa từng thay đổi." Bộ phim có khác biệt đáng kể về chủ đề so với cuốn sách khi nguyên tác đi sâu vào phản bác lại các chuẩn mực giai cấp và giới tính, còn bản chuyển thể lại tập trung xoay quanh tình yêu và sự thuỷ chung, cũng như những tác động mang tính tàn phá của chiến tranh.
printf("%d / %d = %f \n", b, a, b / (double)a);
Lâu đài bay của pháp sư Howl có buổi công chiếu đầu tiên trên thế giới tại Liên hoan phim Venezia vào ngày 5 tháng 9 năm 2004 và ra mắt các rạp chiếu Nhật Bản vào ngày 20 tháng 11 năm 2004. Phim đã thu về 190 triệu USD tại Nhật Bản và 236 triệu USD trên toàn thế giới, trở thành một trong những phim điện ảnh Nhật Bản có doanh thu cao nhất trong lịch sử. Tác phẩm nhận được sự khen ngợi từ giới phê bình, chủ yếu dành cho mặt hình ảnh và cách Miyazaki thể hiện các chủ đề. Bộ phim được đề cử tại hạng mục Phim hoạt hình hay nhất tại lễ trao giải Oscar lần thứ 78 và giành được một số giải thưởng khác trong đó có bốn giải Tokyo Anime và một giải Nebula cho Kịch bản xuất sắc nhất.
Chủ nghĩa hòa bình
Lâu đài bay của pháp sư Howl có chứa nhiều chủ đề phản chiến mạnh mẽ do ảnh hưởng từ sự phản đối của Miyazaki trước cuộc tấn công Iraq năm 2003.[5][7][8] Khi nhận giải Oscar cho Sen và Chihiro ở thế giới thần bí (2001), ông chia sẻ rằng mình "cực kì phẫn nộ [với cuộc chiến tranh Iraq]. Vậy nên [ông] cảm thấy có phần do dự khi nhận giải thưởng này."[5] Miyazaki tự nhận là một người theo chủ nghĩa hòa bình.[7][8][9] Vào đêm trước khi cuộc Chiến tranh Iraq bùng nổ, Miyazaki quyết định làm một bộ phim mà ông cảm thấy sẽ không được đón nhận tại Hoa Kỳ. Mặc dù tác phẩm vẫn đạt được thành công ở Mỹ, học giả văn học Dani Cavallaro nhận định rằng Miyazaki "tạo nên một bộ phim mà nhìn chung đã gây ra một sự khó chịu nhất định cho các khán giả Mỹ." Trong phim, Quý bà Suliman tỏ ra là một người chỉ vì thích làm tổn thương kẻ khác mà gây ra xung đột[5] và dù bà là người có trí tuệ tinh thông nhưng lại không thể nhận ra tính chất vô nghĩa của cuộc chiến cho tới tận khi bộ phim kết thúc. Điều này cho thấy Miyazaki muốn chỉ ra rằng nguyên nhân dẫn đến những cuộc xung đột trong thế giới thực cũng có phần ngẫu nhiên và chúng được thúc đẩy bởi tham vọng của những kẻ có đầu óc khó đoán.[10] Cavallaro cho rằng cách cuộc chiến được tái hiện trong phim mang lại "một hương vị đắng không thể nhầm lẫn",[5] cũng như sự hiện diện của quân đội và chiến tranh đã được làm nổi bật trong bộ phim. Các nhân tố có liên quan đến quân đội được tô đậm ngay từ những bản phác thảo ý tưởng ban đầu, hay như trong phim, những người lính trong quân phục trở nên nổi bật một cách có chủ đích trên nền một khu thương mại đông đúc, nhộn nhịp.[11]

Lâu đài bay của pháp sư Howl được khắc hoạ là một vũ trụ không có những nhân vật phản diện và anh hùng rõ ràng; thay vào đó, các nhân vật có chiều sâu phức tạp, bên cạnh đó ngay cả những nhân vật ban đầu được miêu tả theo chiều hướng tiêu cực như Howl về sau cũng cho thấy khả năng thay đổi.[12] Dù vậy, Matt Kimmich nhận định rằng thông điệp giản đơn của bộ phim chỉ là "chiến tranh là xấu."[9] Cảnh Sophie đang đứng giữa cánh đồng hoa tuyệt đẹp thì trên bầu trời bỗng xuất hiện một tàu bay quân sự đã "buộc tội đế chế cầm quyền là kẻ hủy diệt nền hòa bình."[13] Sự khắc hoạ này trái ngược hẳn với các tác phẩm khác của Miyazaki như Mononoke Hime (1997), vốn thường chỉ trích xung đột quân sự theo một cách khác biệt hơn. Andrew Osmond cho rằng: "Lập trường phản đối chiến tranh đầy thành thực của Howl được thể hiện như thể phản đối kẻ cầm quyền là lựa chọn duy nhất, khi anh chiến đấu chống lại cả hai phe và trở thành nỗi kinh hoàng tồi tệ nhất cho tất cả bọn họ", dưới hình dạng của một con chim dữ tợn. Howl chấp nhận mạo hiểm chính con người mình khi biến hình thành một con thú, còn Calcifer nói rằng sớm muộn anh sẽ không thể quay trở lại hình dạng con người. Ngược lại, nhân vật Ashitaka trong Mononoke Hime cố gắng chiến đấu với vết thương ma quỷ cho anh sức mạnh phi thường nhưng đồng thời cũng khiến anh đau đớn, ngoài ra anh còn cố gắng thương lượng một nền hòa bình cho hai phe đối địch. Osmond nhận định cả hai bộ phim đều chỉ ra rằng nam tính cũng có các giới hạn như những gì Howl và Ashitaka đã minh chứng.[9]

Khả năng bay lượn và sự phê bình nền văn minh hiện đại
Giống như một số tác phẩm khác của Miyazaki,[12] Lâu đài bay của pháp sư Howl phản ánh niềm đam mê của vị đạo diễn đối với khả năng bay lượn. Điều này thể hiện qua một số tàu bay có thiết kế sáng tạo trong phim, cũng như việc Howl biến hình thành một con chim. Sau này, Miyazaki đã lựa chọn bay lượn làm chủ đề chính trong bộ phim Kaze Tachinu (2013). Vị đạo diễn chia sẻ rằng ngày nhỏ ông thấy rất thích thú với máy bay quân sự, nhưng ông dần trở nên căm ghét chúng do chúng được tạo ra vì mục đích hủy diệt. Do đó, trong Lâu đài bay của pháp sư Howl có cả hình ảnh của một chiếc "tàu bay" vô hại, đẹp đẽ và những máy bay quân sự to lớn, xấu xí, chuyên gieo rắc sự phá huỷ. Cavallaro viết rằng Miyazaki muốn "tái hiện khả năng bay lượn như là một điều đáng ngưỡng mộ và nể phục", nhưng đồng thời ông cũng không "[ngó lơ] cách nó bị lạm dụng bởi các chiến lược gia và nhà cầm quyền vô đạo đức."[14]

Cách nhìn nhận có chút khác biệt về khả năng bay lượn của Miyazaki là một trong những sự phê bình của ông về xã hội và công nghệ hiện đại nói chung. Margaret Talbot viết rằng ngoài đời Miyazaki tỏ ra "cực kì không hài lòng với cuộc sống hiện đại," đặc biệt là trước những tác động của công nghệ và sự xa rời thiên nhiên của con người.[12] Nhiều bộ phim của ông cho thấy thái độ ngạo mạn về trình độ công nghệ chính là gốc rễ của cái ác.[15] Những chiếc tàu chiến trong phim được miêu tả là "có ngoại hình hiện đại đầy bóng bẩy và ra vẻ chính nghĩa," nhưng sau đó lại gây ra sự tàn phá nặng nề. Ngược lại, theo Carl và Garrath Wilson, lâu đài vừa như một vật thể sống vừa không của Howl thể hiện "sự diễn giải theo lối Đạo giáo của Miyazaki rằng muốn phát triển kinh tế và xã hội dựa trên công nghiệp thì cần phải hoà hợp với tự nhiên".[16] Antonio Lioi viết rằng những cảnh tượng đẹp đẽ thường được Miyazaki khắc hoạ trái ngược hẳn so với những cảnh có chứa các biểu tượng của nền văn minh hiện đại, chẳng hạn như khi thế giới mộng mơ của Sophie bị một cỗ máy chiến tranh xen vào. Tạo ra sự tương phản này là một cách để Miyazaki bày tỏ sự phê bình sinh thái của mình về nền văn minh hiện đại, nhưng thay vào đó ông cũng mang đến những khung phim với phong cảnh thiên nhiên tươi đẹp.[13]

Tuổi già và lòng trắc ẩn
Miyazaki cho rằng một khía cạnh hấp dẫn trong Lâu đài bay của pháp sư Howl đó là tuổi già được tái hiện một cách khá tích cực. Bị bùa phép của mụ phù thủy biến thành bà già thậm chí giúp Sophie cảm thấy dễ dàng nói ra suy nghĩ của mình hơn. Theo Miyazaki, không giống như trong Lâu đài bay của pháp sư Howl, các cụ bà ít khi được thống trị màn ảnh, điều khiến ý tưởng trong bộ phim của ông có phần mạo hiểm.[12] Elizabeth Parsons nhận định tác phẩm đã phá bỏ định kiến "tuổi già chỉ toàn mang lại những điểm kém thu hút", khi Sophie già nua do trúng bùa phép nhưng lại có thể giải cứu hai chàng trai tuấn tú (cuối cùng đều đem lòng yêu cô) và vô tình giúp vương quốc của cô kết thúc chiến tranh. Những việc Sophie làm thường là các công việc của người bà, chẳng hạn như đối xử tốt và săn sóc những người xung quanh, hoặc thường xuyên tham gia làm công việc nhà; dù vậy, chúng được miêu tả như là những việc làm mạnh mẽ và lớn lao.[17] Sophie là một trong những nữ chính mạnh mẽ trong các tác phẩm của Miyazaki.[13] Theo Parsons, điều này cũng mang lại yếu tố nữ quyền cho bộ phim. Ngoài ra, dù Sophie tự nhận là người giúp việc để hợp lý hoá sự có mặt của mình trong toà lâu đài, nhưng sau đó những công việc nhà trong phim vẫn được phân chia công bằng, qua đó càng củng cố thêm cho yếu tố nữ quyền của tác phẩm.[17]

Năm 2013, Miyazaki chia sẻ rằng Lâu đài bay của pháp sư Howl là tác phẩm yêu thích của ông trong số những đứa con tinh thần của mình. Ông giải thích: "Tôi muốn truyền đi thông điệp rằng cuộc đời là đáng sống, và tôi nghĩ điều đó chưa từng thay đổi." Trong phim, Sophie đã vượt qua mọi khó khăn khi học cách đặt hạnh phúc của những người mà cô yêu thương lên trên lợi ích của bản thân, một phẩm chất mà Miyazaki gọi là sự tận tâm. Một số nhân vật chính trong các tác phẩm của Miyazaki như Ashitaka và San trong Mononoke Hime hay Sheeta và Pazu trong Laputa: Lâu đài trên không (1986) đã tìm được cách sống sót khi nhận ra bài học tương tự. Cavallaro cho rằng Miyazaki đã giảng giải bài học đạo lý này xuyên suốt bộ phim nhằm diễn tả khả năng động lòng trắc ẩn của con người, chẳng hạn như khi Đầu củ cải che ô cho Sophie lúc trời đổ mưa.[18] Howl từ một nhân vật ích kỷ và chỉ chăm lo cho ngoại hình của mình cũng đã học cách đặt người khác lên trước bản thân. Khi Quý bà Suliman biến Phù thủy Vùng hoang địa trở lại hình dạng thật của mụ là một bà lão già nua, Sophie đã cho mụ phù thuỷ một chỗ ở và chăm sóc cho mụ dù chính bà ta đã ếm lời nguyền lên cô, qua đó ý niệm về lòng nhân ái càng được thể hiện rõ hơn. Mụ phù thủy sau đó suýt nữa đã giết chết Howl vì hành động ích kỷ của mình, nhưng tới cuối lại góp công cứu toà lâu đài. Parsons viết: "Trên cán cân công bằng của Miyazaki, các cụ bà có thể vừa mạnh mẽ vừa mềm yếu, vừa tích cực mà cũng vừa tiêu cực, biết yêu thương nhưng cũng tỏ ra ích kỷ, bị chỉ trích nhưng cũng được yêu quý; nói tóm lại, họ không dễ để phân loại hay đưa vào khuôn mẫu, đồng thời cũng không thể bị coi là những kẻ gian tà hư cấu dù mang hình dạng của một phù thủy xấu xa." Các nhân vật này cũng được trao nhiều không gian trong phim với tư cách là người chủ động định đoạt số phận của mình, một điều ít thấy trong các bộ phim phương Tây.[17]

Sản xuất
Ảnh Miyazaki cầm một chiếc microphone
Đạo diễn kiêm biên kịch của bộ phim, Miyazaki Hayao, năm 2009
Nhà sản xuất Suzuki Toshio tại buổi công chiếu bộ phim
Nhà sản xuất Suzuki Toshio tại buổi công chiếu bộ phim
Tháng 9 năm 2001, Studio Ghibli đưa ra thông báo tiến hành sản xuất hai bộ phim. Bộ phim thứ nhất mang tên Loài mèo trả ơn và tác phẩm thứ hai là bản chuyển thể từ tiểu thuyết Lâu đài bay của pháp sư Howl của Diana Wynne Jones. Có nguồn tin cho rằng Miyazaki đã nảy ra ý tưởng thực hiện Lâu đài bay của pháp sư Howl khi đến thăm chợ Giáng sinh Strasbourg.[19] Suzuki Toshio, nhà sản xuất của Lâu đài bay của pháp sư Howl, cho biết Miyazaki đã nảy sinh cảm hứng để thực hiện bộ phim khi đọc cuốn tiểu thuyết của Jones và ông cảm thấy ấn tượng mạnh với hình ảnh một toà lâu đài bay lượn trên đồng quê.[20] Trong khi cuốn tiểu thuyết không giải thích cách toà lâu đài di chuyển thì Miyazaki lại muốn tìm hiểu xem nó có thể chuyển động như thế nào, do đó ông nghĩ ra hình ảnh toà lâu đài di chuyển bằng chân gà.[12] Toà lâu đài di động với hình dạng phức tạp tự biến đổi và tái cấu trúc lại nhiều lần trong suốt bộ phim để phù hợp với tính tình có phần lập dị của Howl, cũng như để thích ứng trong nhiều trường hợp khác nhau. Cấu trúc cơ bản của toà lâu đài gồm hơn 80 phần, trong đó có một cái lưỡi ve vẩy, các tháp canh, bánh răng cưa và chân gà, tất cả đều được tái hiện như là những vật thể kỹ thuật số.[19]

Ban đầu, Hosoda Mamoru từ hãng sản xuất phim hoạt hình Toei Animation được chọn làm đạo diễn cho Lâu đài bay của pháp sư Howl, nhưng ông quyết định rời bỏ dự án sau khi nhiều ý tưởng của mình dành cho bộ phim không nhận được cái gật đầu từ các nhà điều hành của Studio Ghibli. Quá trình sản xuất tác phẩm bị gác lại cho đến khi Miyazaki tiếp quản dự án.[21] Bộ phim được tiếp tục tiến hành sản xuất vào tháng 2 năm 2003,[19] dự kiến hoàn thành vào mùa xuân năm 2004 và phát hành vào mùa hè cùng năm.[21]

Để nghiên cứu các công trình kiến trúc và khung cảnh nhằm dựng bối cảnh cho bộ phim, Miyazaki đã đến thăm hai xã Colmar và Riquewihr thuộc vùng Alsace của Pháp. Miyazaki còn lấy cảm hứng từ các ý tưởng về công nghệ tương lai trong những tác phẩm của Albert Robida.[19] Các nhà bình luận cho rằng hình ảnh trong phim của Miyazaki chịu ảnh hưởng từ niềm yêu thích của ông đối với những bức hoạ theo phong cách "nghệ thuật ảo ảnh" châu Âu thế kỷ 19.[22] Suzuki cho rằng, không giống như nhiều bộ phim phương Tây thường đưa hình ảnh đi "từ cái chung chung [đến] cái cụ thể," Miyazaki sử dụng lối tiếp cận độc đáo của Nhật Bản, đó là bắt đầu với một hình ảnh rất cụ thể và bắt đầu chuyển cảnh từ đó. Tuy nhiên, Lâu đài bay của pháp sư Howl cũng như các bộ phim của Miyazaki đều chú trọng việc sử dụng các hình ảnh chân thực theo cách không giống với những tác phẩm anime khác.[12]

Studio Ghibli sản xuất bộ phim dưới dạng kỹ thuật số, tuy nhiên họ vẽ và tô màu các bối cảnh nền bằng tay trước khi đem số hóa, còn các nhân vật cũng được vẽ tay trước khi được quét để đưa vào máy tính.[19] 1400 bảng vẽ minh hoạ cốt truyện cho bộ phim được hoàn thiện vào ngày 16 tháng 1 năm 2004.[23] Ngày 25 tháng 6, công đoạn tạo khung chuyển tiếp hoàn tất và khâu kiểm duyệt được hoàn thành vào ngày 26 tháng 6.[24] Studio Ghibli sử dụng công nghệ kỹ thuật số để cho chạy nhiều bản sao của các thành phần tĩnh trong một cảnh; quy trình này nhằm tránh sự rời rạc giữa các khung hình tĩnh khác nhau, tuy nhiên cách làm này lại tạo ra cảm giác thiếu chân thực. Do đó, hãng phim chọn cách sửa đổi thủ công các hình ảnh vốn đã được chỉnh sửa kỹ thuật số để mang lại cảm giác của một hình ảnh vẽ tay.[25]

Giống như các bộ phim khác của Studio Ghibli, Lâu đài bay của pháp sư Howl cũng do hãng này đồng sản xuất với các công ty khác, đó là Tokuma Shoten, Nippon Television Network, Dentsu, Buena Vista Home Entertainment, Mitsubishi và Toho.[1]

So sánh giữa phim và tiểu thuyết
Bộ phim có một số điểm khác biệt so với tiểu thuyết, một phần do hai dạng phương tiện truyền thông này có nhiều đòi hỏi khác nhau. Cuốn tiểu thuyết của Jones sở hữu dàn nhân vật đồ sộ cũng như một vài tình tiết truyện quá phức tạp để có thể chuyển thể lên phim ảnh.[26] Do đó, một số nhân vật như cô em út của Sophie là Martha đã được lược bỏ, giống như tình tiết Markl tán tỉnh Sophie (trong tiểu thuyết nhân vật này có tên là Michael và được miêu tả là một chàng thanh niên chứ không phải là một cậu bé).[27] Jones đã có cuộc thảo luận về bộ phim với đại diện của Studio Ghibli nhưng không đóng góp hay tham gia vào việc sản xuất phim. Miyazaki đến Anh vào mùa hè năm 2004 để chiếu riêng cho Jones xem bản chuyển thể điện ảnh đã hoàn thành. Cảm nghĩ của bà được trích lại như sau: "Thật ngoài sức tưởng tượng. Không, tôi đã không có ý kiến đóng góp nào—tôi viết sách chứ không làm phim. Đúng vậy, bộ phim có điểm khác biệt so với cuốn sách—sự thực là nó có thể sẽ rất khác, nhưng nên là như vậy. Đây vẫn sẽ là một bộ phim tuyệt vời."[28]

Lâu đài của Howl trong tiểu thuyết được mô tả là một tòa tháp phù thuỷ cao lớn, tăm tối và tràn đầy sát khí, khác xa với hình ảnh phức tạp trong phim. Lâu đài trong phim có thể coi là một sự giễu nhại những loại máy móc vốn chạy bằng cả động cơ hơi nước lẫn phép thuật trong tác phẩm. Trong phim, toà lâu đài là một "khối ghép tròn xoay được kết hợp từ ống khói, mái nhà, ống dẫn hơi nước và nhiều bộ phận phụ kỳ lạ khác, tất cả được chống đỡ bởi những chiếc chân chim làm từ máy móc", giống như túp lều của nhân vật Baba Yaga trong truyện truyền thuyết nổi tiếng của người Slav. Lâu đài hao hao giống một vật thể sống và được khắc hoạ như thể có sự sống. Tương tự, Calcifer trong cuốn sách là một nhân vật độc ác, không có vẻ ngoài và tính cách dễ mến giống như trong phim.[27] Cả bộ phim và cuốn tiểu thuyết đều muốn truyền tải rằng các yếu tố kỳ ảo cũng chỉ là những điều hết sức bình thường. Mặc dù các nhân vật được đặt trong một vũ trụ giả tưởng nhưng khán giả vẫn hay thấy họ làm các công việc thường ngày như nấu bữa sáng hay giặt giũ, trái ngược với các hành động lớn lao mang tính anh hùng điển hình trong một vũ trụ giả tưởng.[29] Jones tạo ra một sự chia cắt trong bối cảnh giả tưởng của cuốn tiểu thuyết khi cho các nhân vật du hành đến xứ Wales, một địa điểm thuộc thế giới thực. Trong khi đó, bản chuyển thể điện ảnh tránh sự rẽ nhánh này và duy trì liên tục bối cảnh giả tưởng.[30]

Sự bổ sung lớn nhất của Miyazaki vào cốt truyện đó là nâng tầm ảnh hưởng của cuộc chiến tranh. Trong cuốn sách, chiến tranh chỉ được đề cập một cách gián tiếp khi nhà vua lệnh cho Howl đi tìm người em trai mất tích của ông là Justin, vì ông cần tới tài quân sự của Justin cho cuộc chiến sắp tới. Howl thường xuyên vắng mặt là vì thói trăng hoa của anh, điều khiến Sophie cảm thấy anh là một con người nông cạn và hèn nhát. Tuy nhiên, trong phim, Howl thường vắng nhà để phá vỡ kế hoạch chiến đấu của quân đội cả hai phe, dưới hình dạng một con chim khổng lồ.[31]

Sự thay đổi trong cốt truyện này cũng khiến cho vai trò của một số nhân vật có sự khác nhau giữa tiểu thuyết và phim. Trong cuốn sách, Phù thuỷ Vùng hoang địa là nhân vật phản diện chính, còn khi lên phim, mụ bị ma thuật của Quý bà Suliman biến thành một bà già hoàn toàn vô hại và gợi lên sự đồng cảm ở cả Sophie lẫn các khán giả. Bộ phim đã biến hai nhân vật trong tiểu thuyết, cô Penstemmon và phù thủy Suliman, thành một nhân vật duy nhất, Quý bà Suliman. Trong phim, dù Suliman gần như chính là kiểu nhân vật phản diện truyền thống nhưng bà được cho là có động cơ không rõ ràng, ngoài ra các nhà phê bình cũng nhận định rằng chiến tranh mới là nhân vật phản diện thực sự. Thói trăng hoa, phóng đãng vốn là một phần quan trọng trong tính cách của Howl được lược bỏ khi lên phim. Trong khi đó, tính cách của Sophie trở nên thông thường hơn; cô ít gắt gỏng và thẳng thắn hơn, đồng thời cũng bày tỏ tình yêu của mình với Howl sớm hơn và trực diện hơn.[31] Tình tiết truyện thể hiện rằng Sophie là một phù thủy quyền năng tự thân không xuất hiện trong phim mặc dù cô vẫn cho thấy khả năng kiểm soát lời nguyền của mình.[32]

Giữa tiểu thuyết và phim cũng có sự khác biệt về chủ đề trọng tâm. Nhà phê bình Antonia Levi viết rằng trải nghiệm xem phim giống như đọc một tác phẩm fan fiction chất lượng cao và dù các nhân vật và bối cảnh vẫn giữ nguyên nhưng câu chuyện lại khác. Mặc dù câu chuyện luôn bắt đầu với Sophie là một "tù nhân" trong chính hoàn cảnh của cô và định kiến xã hội, nhưng những thử thách mà cô phải đối mặt trong tiểu thuyết và trên phim có phần khác biệt. Levi nói: "Jones dùng Sophie, Howl và Calcifer theo lối truyện cổ tích để kể một câu chuyện phản bác lại những kì vọng về giai cấp và giới tính, còn Miyazaki sử dụng cùng những nhân vật đó để kể câu chuyện về lòng thuỷ chung, tình yêu và chiến tranh."
`;
